QUERY 0:
DESC: ÚLTIMOS 100 POSTS (NO MÁXIMO) DE UMA DETERMINADA HASHTAG NO DIA ATUAL:
SELECT TH.* FROM TWEET_HISTORY TH WHERE TH.HASHTAG = 'devops' 
AND DATE_FORMAT(TH.CREATED_AT, '%Y-%m-%d') = DATE_FORMAT(sysdate(), '%Y-%m-%d') LIMIT 100;
	
QUERY 1:
DESC: RANKING USER X FOLLOWERS
SELECT TH.USER_NAME, TH.FOLLOWERS FROM TWEET_HISTORY TH ORDER BY TH.FOLLOWERS DESC LIMIT 5;	

QUERY 2:
DESC: RANKING LOCALIDADE X TWEETS
SELECT TL.LOCATION, 
       (SELECT COUNT(TWEET) AS TWEETS FROM TWEET_HISTORY WHERE LOCATION = TL.LOCATION) AS TWEETS
FROM (SELECT TH.CODIGO, TH.LOCATION FROM TWEET_HISTORY TH GROUP BY TH.LOCATION) TL ORDER BY TWEETS DESC LIMIT 5;

QUERY 3:
DESC: RANKING HORA X TWEETS
SELECT TL.HORA, 
       (SELECT COUNT(TWEET) AS TWEETS FROM TWEET_HISTORY WHERE time_format(CREATED_AT, '%H') = TL.HORA) AS TWEETS
FROM (SELECT time_format(CREATED_AT, '%H') HORA FROM TWEET_HISTORY GROUP BY HORA) TL ORDER BY TWEETS DESC LIMIT 5;